### PR TITLE
Optimize readLong_b to read 32bit at once from the serial buffer.

### PR DESCRIPTION
**Pull request by astralaster**
This small change does optimize the upload speed from the ez80 to the VDP. The attached benchmark shows upload speed of 227kbits with the current code and 749kbits with my change. You can also "feel" the difference if you start games like rokky.

[agon-bench.zip](https://github.com/breakintoprogram/agon-vdp/files/12677182/agon-bench.zip)

### CODE REVIEW

**Comment by stevesims** [comment]
most awesome

I've already tested this and can confirm that it does indeed deliver the big bandwidth increase

@breakintoprogram please merge ASAP :grin:

**Comment by breakintoprogram** [comment]
Thanks. That looks reasonable to me. I'll merge and test later.

**Comment by theflynn49** [comment]
Awesome. It's surprising (to me) at the first glance that this change makes such a notable difference !

**Comment by stevesims** [comment]
> Awesome. It's surprising (to me) at the first glance that this change makes such a notable difference !

the reason for this I believe is that essentially the previous version was calling `readByte_b` 4 times, each time of which runs thru a `while` loop waiting for a byte to become available.  if the comms buffer were full (or rather just had those 4 bytes available, which is fairly likely), there would always be bytes available so that's 3x the amount of checking loops needed.  additionally the `readBytes` call here would be a simple memory copy, so there's no shuffling of bytes around to form the 32-bit word.

I kinda get why it's a fairly big improvement - and conversely am also still surprised by how big an improvement it is.  :grin:

gives me some ideas for some further improvements that can be made - but those will have to wait a little while.

**Comment by astralaster** [comment]
I was a bit surprised as well. But you have to remember this is a 32bit CPU. It's most happy to fetch 32bit around. It could basically as costly to fetch 32bit at once or just 8bit.

**Pull request merged**
